---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-components
  namespace: argocd
spec:
  description: Project for Core Components
  sourceRepos:
    - https://github.com/open-policy-agent/gatekeeper.git
    - https://github.com/dnascimento/eks-apps
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: gatekeeper-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: core-components
  source:
    repoURL: https://github.com/dnascimento/eks-apps
    targetRevision: master
    path: apps
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

